### ISSUE TITLE
Add configuration for default "Official pack" weapons/ammo/etc...

### ISSUE THREAD

**Issue by Twilight13** [LemADEC/GunCus#13]
GunCustomization-1.7.10-3.45.0.22:

Just a suggestion to include .cfgs for all the default "official pack" weapons and ammo so that they can be adjusted/customized. If you add an add-on, such as the Wholy pack, all of the weapons and ammo settings are easily available for adjusting, but there seems to be no way to do so for the default "official" weapons, ammo, etc.

Given that the customization of weapon and ammo attributes are one of the best features of this mod (in my opinion), not allowing configuration of the default weapons and ammo seems like an oversight.

**Comment by LemADEC** [comment]
This is a legacy design decision due to difficulty to install a default pack at that time. You can find the actual parameters from the default pack here: https://github.com/LemADEC/GunCus/blob/master/src/main/java/stuuupiiid/guncusofficial/GunCusOfficial.java#L75
It's still a bit overcomplicated to read, we'll have to find a better solution for that.

**Comment by LemADEC** [comment]
Official pack has been created in dev. We still need to 'install' it before release.

**Comment by LemADEC** [comment]
Fixed in official release
