### ISSUE TITLE
Guns fire in response to a click in the ESC menu.

### ISSUE THREAD

**Issue by Twilight13** [LemADEC/GunCus#17]
When you are in a multiplayer server, and hit the escape key to bring up the menu "Options, Disconnect, etc", if you click on the "Back to Game" button, it will close the menu, as expected, but the gun you are holding also registers it as a left click (Which it is, of course, but it should only count for the menu button click), and fires a shot ( or two or three if you have an automatic/burst fire weapon).

Haven't tested this in single-player, but it's probably the same there.

It's not a big deal, but it can be an irritating waste of ammo for no good reason.

**Comment by LemADEC** [comment]
It's a known limitation of several mods. You need to press Esc to close the menu.
There's no easy fix per say for this.

**Comment by YuRaNnNzZZ** [comment]
~~You can actually check on client if any GUI is opened: `Minecraft.getMinecraft().currentScreen` will be null if no GUI opened.~~ Well, guns already doing that. You may want to switch default branch for repo (because it's 1.6.4 version as for now).

**Comment by YuRaNnNzZZ** [comment]
There's also another bug that related to gui checking: if i press RMB in any gui (even pause menu in the singleplayer!) then screen begins to shaking like as i'm aiming, but if i'm press LMB while "aiming" from the gui then gun will shoot as usual.

**Comment by LemADEC** [comment]
I've added a cool-down when exiting a GUI but the game menu is also 'pausing' the game in SSP, so it's not completely reliable. I'll need a bit more digging...

**Comment by LemADEC** [comment]
The original idea was to allow shooting while player sees it's inventory (chat or straight inventory). This was done using right + left click so it's explicitly different from moving items around.
Practically, it doesn't work with certain GUI that are wrongly reported as own's inventory. Also, scoping bonus is still applied, improving accuracy instead of applying a malus.
This behavior adds more bugs than benefits, so it will be removed in next update.
